### ISSUE TITLE
Copy with line numbers.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gnatstudio#92] opened 2019-10-30 20:01 UTC
Hello,

Consider the following piece of code:

```ada
180.    begin
181.       Element := NonDefini;
182.       Liste := null;
183.       if not AJour and then AutoBal then
184.          Balance;
185.       end if;
186.       if Arbre /= null then
187.          RechercheDans (Arbre);
188.       end if;
189.    end Recherche;
```
When I fold the if block line 183, and I do a simple copy, I get only the displayed lines copied - why not:

```ada
   begin
      Element := NonDefini;
      Liste := null;
      if not AJour and then AutoBal then
      if Arbre /= null then
         RechercheDans (Arbre);
      end if;
   end Recherche;
```
But when I do a copy with line numbers, the lines are shifted:

```ada
180.    begin
181.       Element := NonDefini;
182.       Liste := null;
183.       if not AJour and then AutoBal then
         Balance;
      end if;
184.       if Arbre /= null then
185.          RechercheDans (Arbre);
186.       end if;
187.    end Recherche;
188. 
189.   -- Procédure retournant le premier élément de la liste triée
   end Recherche;
```
Configuration: GPS Community 2019, macOS 10.13.6.

HTH, Pascal.

**Comment by AnthonyLeonardoGracio** [comment] 2019-11-19 13:59
Hello Pascal,

I can't reproduce the "lines are shifted" part: can you explain exactly what did you do to have these lines shifted?

Regards,

**Comment by Blady-Com** [comment] 2019-11-24 09:13
Hello Anthony,
In the following example, when I copy "with line numbers"  lines 80 through 99, I get:
```ada
80.       procedure Strcpy (Target_Ptr, Source_Ptr : Char_Star) is
81.          Target_Temp_Ptr : Char_Star := Target_Ptr;
82.          Source_Temp_Ptr : Char_Star := Source_Ptr;
83.          Element         : C.char;
84.       begin
85.          if Target_Temp_Ptr = null or Source_Temp_Ptr = null then
86.             raise C.Strings.Dereference_Error;
87.          end if;
88. 
89.          loop
90.             Element             := Source_Temp_Ptr.all;
91.             Target_Temp_Ptr.all := Element;
92.             exit when C."=" (Element, C.nul);
93.             Char_Ptrs.Increment (Target_Temp_Ptr);
94.             Char_Ptrs.Increment (Source_Temp_Ptr);
95.          end loop;
96.       end Strcpy;
97.    begin
98.       null; --@ ...
99.    end Test_Pointers;
```
Then, I fold the "if" (line 85) and "loop" (line 89) blocks like the screen capture:
![Capture d’écran 2019-11-24 à 10 01 54](https://user-images.githubusercontent.com/24991522/69492352-1f3fff00-0ea2-11ea-9e40-8f3578ea878c.png)
When I copy "with line numbers" lines 80 through 99, I get:
```ada
80.       procedure Strcpy (Target_Ptr, Source_Ptr : Char_Star) is
81.          Target_Temp_Ptr : Char_Star := Target_Ptr;
82.          Source_Temp_Ptr : Char_Star := Source_Ptr;
83.          Element         : C.char;
84.       begin
85.          if Target_Temp_Ptr = null or Source_Temp_Ptr = null then
            raise C.Strings.Dereference_Error;
         end if;
86. 
87.          loop
            Element             := Source_Temp_Ptr.all;
            Target_Temp_Ptr.all := Element;
            exit when C."=" (Element, C.nul);
            Char_Ptrs.Increment (Target_Temp_Ptr);
            Char_Ptrs.Increment (Source_Temp_Ptr);
         end loop;
88.       end Strcpy;
89.    begin
90.       null; --@ ...
91.    end Test_Pointers;
<...>
```
Line numbers are no more corresponding to source code.

HTH, Pascal.

**Comment by AnthonyLeonardoGracio** [comment] 2019-11-25 09:31
Hello Pascal,

We have changed the way we fold/unfold blocks in newer versions of GS and the behavior has changed since then: copying code that contains folded blocks does not include the 'folded' parts.

We may want to change this actually: ideally, I think that copying folded blocks should also copy what is currently folded. 

What do you think?

**Comment by simonjwright** [comment] 2020-05-23 07:47
Butting in: I’d like to see the use case that justified **not** copying the folded blocks

**Comment by AnthonyLeonardoGracio** [comment] 2020-05-25 09:52
@simonjwright I don't remember a use-case that justified it to be honnest, it was probably a bug that we have introduced when changing the way we handle folding/unfolding (we now use invisible GtkTextTag instead of manually removing/adding the code when folding/unfolding).

**Comment by AnthonyLeonardoGracio** [comment] 2023-05-19 12:43
This is now fixed in the latest versions of GNAT Studio: copying a folded line will copy the folded contents.

Regards,

**Closed by AnthonyLeonardoGracio** 2023-05-19 12:43 UTC
